sul-dlss/dor-workflow-client

dor-workflow-service.gemspec, lib/dor/services/workflow_service.rb, spec/workflow_service_spec.rb
This PR implements HTTP persistent connections for the workflow service client. It uses Faraday and the net-http-persistent gems, and only implements persistent connections on the `GET` methods.
Note that you need to ensure that you do not have an oldish version of `webmock` running as it will disable the persistent connections.
Testing is a little tricky but I changed the Apache log output format to include `k=%k %{Keep-Alive}o` -- the `%k` shows which of the n-th requests this is on the same connection, and a successful log trace looks like so:
```
[30/Nov/2015:15:23:32 -0800] "GET /workflow/dor/objects/druid:kv840rx2720/workflows/ HTTP/1.1" 200 2297 k=0 timeout=5, max=100
[30/Nov/2015:15:23:32 -0800] "GET /workflow/dor/objects/druid:kv840rx2720/lifecycle HTTP/1.1" 200 121 k=1 …
```
=> Adds support for HTTP persistent connections

dor-workflow-service.gemspec, lib/dor/services/workflow_service.rb, spec/spec_helper.rb, spec/workflow_service_spec.rb
This PR fixes `count_errored_for_workstep` and `count_queued_for_workstep` which had transposed arguments. I also increased the code coverage and added `simplecov`.
=> Fix for broken count_*_for_workstep APIs

lib/dor/services/workflow_service.rb, lib/dor/workflow_exception.rb, spec/workflow_service_spec.rb
The `dor-services` is very tightly coupled to the internal workings of this class. This PR tries to provide better abstractions that we can use in `dor-services` to avoid assuming e.g. `RestClient` errors.
=> Wrap HTTP client errors in a Dor::WorkflowException class

lib/dor/services/workflow_service.rb, spec/workflow_service_spec.rb
`Dor::WorkflowObject#to_solr` [1] directly accesses the workflow service REST APi. This commit moves this logic upstream.
[1] https://github.com/sul-dlss/dor-services/blob/c672c0b60a74a5b1aa72ad69885638e8b4f34456/lib/dor/models/workflow_object.rb#L48
=> Add count_archived_for_workflow accessor for the number of archived workflows

lib/dor/services/workflow_service.rb
base_url has a trailing slash already
This will eliminate confusion around log messages such as:
```
[2018-08-29T15:11:40.551844 #21948] ERROR -- : Error performing MoabReplicationAuditJob (Job ID: 9fcb94a0-b431-43ae-b45e-51b993545c78) from Resque(moab_replication_audit) in 1516.2ms: Dor::WorkflowException (Failed to retrieve resource: put https://sul-lyberservices-prod.stanford.edu/workflow//dor/objects/druid:jq458kf3115/workflows/preservationAuditWF/preservation-audit (HTTP status 500)):
```
=> Remove slash in rescue message

lib/dor/workflow/client/lifecycle_routes.rb, spec/workflow/client/lifecycle_routes_spec.rb
This will ensure that the workflow server doesn't need to make a call to dor-services-app to get the version
=> Allow querying for a lifecycle for a specific version

lib/dor/workflow/client.rb, lib/dor/workflow/client/workflow_routes.rb, spec/workflow/client/workflow_routes_spec.rb, spec/workflow/client_spec.rb
Added update_error_status to replace update_workflow_error_status without having to pass an empty first argument
Fixes #125
=> Switch update_workflow_error_status to use a non-deprecated endpoint

lib/dor/workflow/client/lifecycle_routes.rb, spec/workflow/client/lifecycle_routes_spec.rb
This allows active_lifecycle to be faster because it doesn't have to lookup the current version in dor-services-app
=> Allow passing version to active_lifecycle

lib/dor/workflow/client/workflow_routes.rb, spec/workflow/client/workflow_routes_spec.rb, spec/workflow/client_spec.rb
Nothing in DLSS uses this so it doesn't need to be a public method
=> Deprecate workflow_xml

Gemfile, lib/dor/missing_workflow.rb, lib/dor/missing_workflow_exception.rb, lib/dor/workflow/client/requestor.rb, lib/dor/workflow_exception.rb, spec/workflow/client_spec.rb
Refs sul-dlss/workflow-server-rails#297
Add `Dor::MissingWorkflow` exception as subclass of Dor::WorkflowException so existing code can continue to rescue `Dor::MissingWorkflow` without changing code downstream.
Also includes the following opportunistic work:
* Remove redundant simplecov dependency
* Remove (apparently) unnecessary explicit scoping for RuntimeError
=> Raise `Dor::MissingWorkflow` when workflow service returns 404

lib/dor/workflow/response/workflows.rb, spec/models/response/workflows_spec.rb
This will help dor-services-app answer 'are there any errors' without needing to know the implementation.
See: https://github.com/sul-dlss/dor-services-app/blob/7fb98f10efb7b14c34077da0160489f87acd3a72/app/services/workflow_error_checking_service.rb#L23-L25
=> Provide a way to get all errors for a version

lib/dor/workflow/client/version_routes.rb, spec/workflow/client/version_routes_spec.rb
also deprecate passing the repo argument to close_version
=> Use the non-deprecated route for closing a version

README.md, lib/dor/workflow/client.rb, lib/dor/workflow/client/status.rb, spec/workflow/client/status_spec.rb
This is extracted from dor-serivces Dor::StatusService, because it is about workflow, not the persisted models
=> Add a method for extracting status for an object

lib/dor/workflow/client.rb
Otherwise you pass a different druid, but the status service has the previously passed druid
=> A new status service should be returned on each invocation

README.md, lib/dor/workflow/client/lifecycle_routes.rb, lib/dor/workflow/client/status.rb, spec/workflow/client/lifecycle_routes_spec.rb, spec/workflow/client_spec.rb
Removes the repo parameter we're trying to deprecate from the lifecycle routes and milstones.
README
Note: I believe that argo is currently using the milestones out of solr, however it may need to be updated to get the appropriate lifecycle xml request. This should be tested in stage.
=> Remove repo from lifecycle routes and milestones

lib/dor/workflow/client/workflow_routes.rb, spec/workflow/client_spec.rb
This will allow Hydrus to pass a version, which will allow workflow-server-app to be decoupled from dor-services-app
=> Pass the object version when deleting a workflow

lib/dor/workflow/client/status.rb, spec/workflow/client/status_spec.rb
closes #169
Reduce confusion over the data type for version.
Unit
NA
=> Allows status to accept a string or integer version.

dor-workflow-client.gemspec
=> Relax activesupport dependency to include 7

dor-workflow-client.gemspec
simplecov later versions work with codeclimate test report runner.
=> simplecov no longer needs to be pinned to 0.17

dor-workflow-client.gemspec, lib/dor/workflow/client.rb, lib/dor/workflow/client/connection_factory.rb
This drops the redirect ability, because faraday_middleware doesn't support faraday 2, but we don't actually use that capability: https://github.com/sul-dlss/workflow-server-rails/blob/main/app/controllers/workflows_controller.rb#L23-L26
=> [HOLD] [MAJOR] Upgrade to faraday 2

lib/dor/workflow/client/workflow_routes.rb, spec/workflow/client/workflow_routes_spec.rb, spec/workflow/client_spec.rb
The new path doesn't have a repository in the url. See https://github.com/sul-dlss/workflow-server-rails/pull/562
Most of the other public methods prefer to be called with kwargs, so standardize on that.
test suite.
=> [semver:minor] allow deleting using kwargs and the new path

dor-workflow-client.gemspec
We use at least 3.0 everywhere now.
=> require ruby 3.0 or higher

lib/dor/workflow/response/workflow.rb, spec/dor/workflow/response/workflow_spec.rb
So that the status of a workflow can be determined for a specific version.
Unit
=> Adds completed_for? method to workflow response.

lib/dor/workflow/client/status.rb, spec/dor/workflow/client/status_spec.rb
Goes with https://github.com/sul-dlss/argo/issues/4387 to no longer track or display a "described" milestone. 
Unit.
=> Deprecate 'described' lifecycle milestone

lib/dor/workflow/response/workflow.rb, spec/dor/workflow/response/workflow_spec.rb
refs https://github.com/sul-dlss/dor-services-app/issues/4851
To allow getting incomplete processes so that VersionService can determine if workflows are done-enough.
Unit
=> Adds support for getting incomplete processes from workflow response.

.gitignore, README.md, bin/console, lib/dor/workflow/client.rb, lib/dor/workflow/client/lifecycle_routes.rb, lib/dor/workflow/client/version_routes.rb, lib/dor/workflow/client/workflow_routes.rb, lib/dor/workflow/response/process.rb, spec/dor/workflow/client/workflow_routes_spec.rb, spec/dor/workflow/client_spec.rb, spec/dor/workflow/response/process_spec.rb
Fixes #298 
~~HOLD until workflow-server-rails changes are merged and deployed.~~
Allow the user to send in optional workflow metadata variables.
Note that the response from workflow-server-rails for workflows with metadata just adds to the existing XML.  We add a new method to parse out the metadata for any step into a hash for the consumer (it comes in via the XML response as JSON, which is what is stored in the workflow-server-rails database).
Requires sul-dlss/workflow-server-rails#745 to be released 
Also:
- add the ability to test gem on the console (we do this in other gems too)
- add the missing 'all_workflows' route to base client and a spec for it
1. New specs
2. Tested on localhost against local workflow-server-rails running new workflow-server variables work
=> add metadata param for workflow variables

lib/dor/workflow/client.rb
the relevant code is now here: https://github.com/sul-dlss/workflow-server-rails/blob/d104a2f116b2852ced37358deae698a9697e4b95/app/models/workflow_step.rb#L9
java workflow service was retired in 2017 ☕ 
discovered while looking up relevant code for review of https://github.com/sul-dlss/lyber-core/pull/167
n/a, comment update only
=> update very outdated comment

lib/dor/workflow/client/workflow_routes.rb, spec/dor/workflow/client/workflow_routes_spec.rb
If you use the wrong dor-workflow-client method to set the error status, you will get the error message being put in the wrong place (in the note field, displays in green in argo, instead of the error field, displays in red).
In addition, we noticed that the queuing of steps doesn't seem to work correctly and allows the next step to proceed even when the previous is an error.  
This should prevent that from happening at the client level.
Updated spec
=> raise an error when setting an error status incorrectly

Gemfile.lock, dor-workflow-client.gemspec
So that it can be used with a Rails 8 app.
=> Update activesupport pinning.

lib/dor/workflow/client.rb, lib/dor/workflow/client/queues.rb, spec/dor/workflow/client_spec.rb
So the ETD app has a way to retry catalog-status runs if Folio is borked.
CI, and used successfully in stage.
=> Add endpoint for querying objects erroring at a given step
