sul-dlss/dor-workflow-client

dor-workflow-service.gemspec
lib/dor/services/workflow_service.rb
lib/dor/workflow_version.rb

See https://github.com/rails/rails/issues/17936

Fix for newest rails (v4.2.0)

---

lib/dor/services/workflow_service.rb
spec/workflow_service_spec.rb

These will be used in sul-dlss/preservation_robots

Expose count_objects_in_step method

---

.travis.yml

all infrastructure projects are on 2.5.3

Remove old ruby versions

---

lib/dor/services/workflow_service.rb
spec/spec_helper.rb
spec/workflow_service_spec.rb

 Select values from the most recent version 

---

lib/dor/services/workflow_service.rb
lib/dor/workflow_version.rb

Switches to net:http from net:http:persistent. Bumps version to 2.10.2."

---

lib/dor/services/workflow_service.rb
spec/workflow_service_spec.rb

Deprecate count_archived_for_workflow

---

spec/workflow_service_spec.rb

See https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/described_class.rb

Use described_class for specs

---

lib/dor/models/response/update.rb
lib/dor/workflow/client.rb
spec/workflow/client_spec.rb

Model the update response

---

lib/dor/workflow/client/workflow_routes.rb
spec/workflow/client/connection_factory_spec.rb
spec/workflow/client_spec.rb

The workflow service doesn't do anything with this

Remove the create-ds parameter

---

lib/dor/workflow/client/workflow_routes.rb

This should have been in #100 but was overlooked

Remove some further create_ds code

---

lib/dor/workflow/client/workflow_routes.rb
spec/workflow/client_spec.rb

Adds support for version parameter when creating workflow.

---

lib/dor/workflow/client.rb
lib/dor/workflow/client/workflow_routes.rb
spec/workflow/client/workflow_routes_spec.rb

Ref https://github.com/sul-dlss/workflow-server-rails/pull/209

Add route for delete all workflow steps

---

.travis.yml
README.md
spec/spec_helper.rb

Fixes #98
(I believe the coverage stats only show after merge to master)

hook up codeclimate and add code coverage badges to README

---

lib/dor/workflow/client/workflow_template.rb
spec/workflow/client/workflow_template_spec.rb

Ref https://github.com/sul-dlss/argo/issues/1578#issuecomment-533581595
Ref https://github.com/sul-dlss/workflow-server-rails/pull/261

Add method to retrieve a list of templates

---

Gemfile
lib/dor/workflow/client/connection_factory.rb
spec/workflow/client_spec.rb

Not the older name, dor-workflow-service

Ensure the user-agent string says dor-workflow-client

---

lib/dor/workflow/response/workflow.rb
spec/models/response/workflow_spec.rb

Extracted from https://github.com/sul-dlss/dor-services/pull/678

Add a completed? method on the workflow

---

lib/dor/workflow/client.rb

Added new status "started" as a valid status.
Refs https://github.com/sul-dlss/common-accessioning/issues/515

Added started as a valid status.

---

lib/dor/workflow/client/status.rb
spec/workflow/client/status_spec.rb

This will be used for indexing

Add Status#display_simplified

---

lib/dor/workflow/client/workflow_routes.rb

Add note about Hydrus being the only user of delete workflow

---

lib/dor/workflow/client/lifecycle_routes.rb

To stop lying.
The code comment was.

Correct YARD for `#milestones`

---

lib/dor/workflow/response/process.rb
lib/dor/workflow/response/workflow.rb
spec/models/response/process_spec.rb
spec/models/response/workflow_spec.rb

It is no longer used by the server.
Test suite
n/a

Deprecate the repository property

---

README.md
dor-workflow-client.gemspec

Update default branch references from master to main

---

spec/workflow/client_spec.rb

Fix test mock

---

README.md

Fix phrasing of README

---

.circleci/config.yml
lib/dor/workflow/client/workflow_routes.rb

test on ruby 3

---

.circleci/config.yml
Gemfile

Switched to sul-dlss/ruby-rails orb for circleci config.

---

spec/models/response/workflow_spec.rb

The previous description was not for the right method.

Update spec description

---

lib/dor/workflow/client.rb
lib/dor/workflow/client/lifecycle_routes.rb
lib/dor/workflow/client/queues.rb
lib/dor/workflow/client/version_routes.rb
lib/dor/workflow/client/workflow_routes.rb
lib/dor/workflow/response/process.rb
lib/dor/workflow/response/workflow.rb
spec/models/response/process_spec.rb
spec/models/response/workflow_spec.rb
spec/workflow/client/lifecycle_routes_spec.rb
spec/workflow/client/version_routes_spec.rb
spec/workflow/client_spec.rb

Clean up old stuff that we don't use anymore.
Test suite

[semver:major] Remove deprecations

---

.rubocop.yml

Add new rubocops.

---

lib/dor/workflow/client/status.rb

I tested this PR by pointing [Argo at this branch](https://github.com/sul-dlss/argo/compare/main...workflow-client-v6), deploying Argo, and running the bulk metadata update integration test which we believe should test the code path changed here.

Refactor Status class for hopefully increased legibility and reasoning

---

lib/dor/workflow/client/workflow_template.rb
spec/dor/workflow/client/workflow_template_spec.rb

Restore templates method.

---

lib/dor/workflow/client.rb
lib/dor/workflow/client/workflow_routes.rb
spec/dor/workflow/client/workflow_routes_spec.rb

see https://github.com/sul-dlss/workflow-server-rails/issues/782
https://github.com/sul-dlss/workflow-server-rails/pull/787 also needs merge
QA + rspec

add skip-all
